### ISSUE TITLE
Scss error when compiling default theme

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow-external-links#27]
Leaving this here, still investigating a fix.

When I try to include this gem's default theme the css won't compile:

```
Sass::SyntaxError
Invalid CSS after "...    line-height": expected ")", was ": 1.3em"
```

pointing to 

stylesheets/pageflow/external_links/themes/default.scss at line 70

```
line-height: 1.3em
```

**Comment by tf** [comment]
Yes, forgot about this. You are completely right. The `default.scss` file already depends on Sass 3.4 and some helpers from the coming configurable Pageflow default theme. There is a separate `themes/legacy.scss` file which you can use. I'll update the readme.

**Comment by tilsammans** [comment]
Got it!
