### ISSUE TITLE
Field of view adjust doesn't work

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow-external-links#29]
When I click the 'Adjust Field of View' button for an external site thumbnail, nothing happens and this is shown in the console:

```
TypeError: this.model.getFilePosition is not a function. (In 'this.model.getFilePosition(this.options.propertyName,"y")', 'this.model.getFilePosition' is undefined)
```

(issue transferred from codevise/pageflow-linkmap-page#6)

**Comment by tf** [comment]
The [`imagePositioning: false` option](https://github.com/codevise/pageflow-external-links/blob/master/app/assets/javascripts/pageflow/external_links/editor/views/configuration_editor.js#L11) has to be changed to `positioning: false` to prevent the button from being displayed.

The option has been renamed a long time ago and obviously nobody has noticed the remaining usage of the old name here. Can you take a look and test whether this solves the issue?

**Comment by tilsammans** [comment]
Seems to work, the button is gone. I will submit a pull request.

I found two references to `imagePositioning` by the way.
