### ISSUE TITLE
external links page-type not visible

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow-external-links#35]
Hello there,
i just installed two of the open source page-types `external-links` and `linkmap-page`.
I did everything mentioned in the installation-guide and configured some external test-links.
Still there is no Page-Type visible as shown in the screenshot:
<img width="420" alt="bildschirmfoto 2017-09-07 um 13 38 41" src="https://user-images.githubusercontent.com/15860150/30161685-e9b08078-93d1-11e7-8a0b-5a55ab4b4e8b.png">

am i missing something? Since i can actually configure the external links i think, that the installation went right.

[edit]
The same Issue seems to appear with "internal-links". I Installed it how the tutorial told me to und found myself only with the page-type "Multiple-Choice" where i expected Mosaik to be (shown in the updated screenshot).
I guess i left some configurations out which are not documented?

Best regards,
Ronald

**Comment by tf** [comment]
Hi Ronald,

sorry for the late reply. What version of the gems are you using? The instructions changed between 0.x and 1.0. So the steps described in the readme on master may not apply to you version. You can switch back to the old versions of the README using the Github tag picker.

Tim

**Comment by nerdusMaximus** [comment]
i am on these Versions:

```
pageflow-external-links (0.4.0)
pageflow-internal-links (0.2.0)
```

**Comment by tf** [comment]
I thought so. So if you look at the readme of that version, you'll see that the page types need to be registered explicitly. You can leave in the `plugin` calls that you already have since they provide additional topics for the editor help etc. I think, those are missing in the documentation of the old version.

**Comment by nerdusMaximus** [comment]
indeed that was it. I already gone mad about this. And as usual such a simple but fatal error on my side.

Tanks alot!

**Comment by tf** [comment]
Great! I've updated the old readme files to also include the plugin registration calls. Now the docs should be correct.
